version: '3.1'

services:
  ghost:
    image: ghost:6-alpine
    ports:
      - "2368:2368"
    env_file:
      - .env
    environment:
      - database__client=${database__client}
      - database__connection__host=${database__connection__host}
      - database__connection__user=${database__connection__user}
      - database__connection__password=${database__connection__password}
      - database__connection__database=${database__connection__database}
      - database__connection__port=${database__connection__port}
      - url=${url}
    restart: unless-stopped
