services:
  - type: web
    name: cms-project
    env: docker
    plan: free
    branch: main
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: url
        value: https://cms-project.onrender.com
